# Generated by Django 5.0.7 on 2024-07-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0002_noticia_texto_markdown_alter_categoria_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticia",
            name="archivo_markdown",
        ),
        migrations.AddField(
            model_name="noticia",
            name="archivo_texto",
            field=models.FileField(blank=True, null=True, upload_to="textos/"),
        ),
    ]
