# Generated by Django 5.0.7 on 2024-07-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0003_remove_noticia_archivo_markdown_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticia",
            name="texto_markdown",
        ),
        migrations.AlterField(
            model_name="noticia",
            name="contenido",
            field=models.TextField(blank=True, null=True),
        ),
    ]
