# Generated by Django 4.2.14 on 2024-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_tag_noticia_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.AddField(
            model_name='noticia',
            name='apellido_usuario',
            field=models.CharField(default='Centurión', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='nombre_usuario',
            field=models.CharField(default='Marco', max_length=100),
            preserve_default=False,
        ),
    ]
